### ISSUE TITLE
Usage of Incorrect Google API with youtube.py

### ISSUE THREAD

**Issue by orangefriday** [pyvideo/data#254]
When you input an incorrect Google API key in youtube.py, it will throw this error.

Traceback (most recent call last):
  File "tools/youtube.py", line 266, in <module>
    main()
  File "tools/youtube.py", line 257, in main
    fetch_list(api_key, args.list)
  File "tools/youtube.py", line 127, in fetch_list
    response_dict = get_response_dict_for_play_list(query_parts)
  File "tools/youtube.py", line 116, in get_response_dict_for_play_list
    handle_errors(response_dict)
  File "tools/youtube.py", line 110, in handle_errors
    raise RuntimeError(error.get('message'))
RuntimeError: Bad Request

**Comment by lgh2** [comment]
I can edit the script to handle this error.

**Comment by lgh2** [comment]
I am going to close this one because the error was raised as the script intended.
